### ISSUE TITLE
Hacktoberfest -> Some errors in swag redeem form

### ISSUE THREAD

**Issue by Aman-zishan** [chec/commerce.js#106]
![hack](https://user-images.githubusercontent.com/55238388/96617026-badf2700-1320-11eb-8cb8-b0d4b511a1c2.PNG)

I noticed that the contributors can **edit** the number of bundles they can get while submitting the **swag redeem** form(I'm not sure if its purposeful ). Also once a form is submitted it is not locked for the next time. I was able to make a successful order even after doing it for more that twice. (That PR was invalid and still the order wasn't cancelled)

Now I'm resubmitting the form with the link of a merged PR.

**Comment by robbieaverill** [comment]
If people abuse that form it'll just be ignored 🙂  Thanks for pointing it out though.
