### ISSUE TITLE
Add example to "Add to cart" docs for using the variant argument

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#120]
It's undocumented at the moment, but accepts an object of this structure:

```js
{
  vrnt_ABC123: opt_234,
  vrnt_BCD234: opt_345,
}
```

Key: variant ID, value: variant option ID.

**Comment by jaepass** [comment]
Fixed by https://github.com/chec/commerce.js/pull/146 and also outdated since variants release
