### ISSUE TITLE
Expose more information in console debugger when 422 errors are encountered

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#124]
Example: https://github.com/chec/cli/issues/39. The console debugger outputs the primary error message from this response, which is "the given data was invalid". There are nested messages which are specific errors underneath this. We could display them in a simple list in the console to help developers to find out what their problems are without having to examine the full response body.

**Comment by jaepass** [comment]
gah tried to take a stab at this but ran into a bunch of npm link issues to run package locally. will try to pick it up again next week

**Comment by robbieaverill** [comment]
Example 422 response from checkout.capture: 
![image](https://user-images.githubusercontent.com/5170590/122307850-f4702e00-cebf-11eb-819b-9d92eeb25611.png)
