### ISSUE TITLE
Add example of using pagination in "list products" method docs

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#135]
https://commercejs.com/docs/sdk/products#list-products

Would be nice to show a short example of how to adjust the page length and page number using `commerce.products.list()`, since it seems to trip devs up occasionally.

**Comment by eufandem** [comment]
Video content idea right there.

**Comment by jaepass** [comment]
Duplicate of https://github.com/chec/commerce.js/issues/121
