### ISSUE TITLE
Update 'add to cart' method signature to support 2021-03-31 API release for variants

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#143]
This release will come with some breaking changes for variants.

https://github.com/chec/commerce.js/blob/master/src/features/cart.js#L77-L91

This method will need to be updated to support the new request arguments:
* `options`: array of variant option IDs
* `variant_id`: string, specific variant ID

We may want to rename `variant` to `data` and let it work for both.

**Comment by robbieaverill** [comment]
cc @ScopeyNZ re: new Commerce.js version to go along with this

**Comment by dvnkshl** [comment]
+1 on renaming to `data` to handle both

**Comment by robbieaverill** [comment]
Can you do a new release @ScopeyNZ?
