### ISSUE TITLE
customer.getOrders Error 500

### ISSUE THREAD

**Issue by zb2oby** [chec/commerce.js#148]
Hi, 

When i call manually "https://api.chec.io//v1/customers/{customer_id}/orders" endpoint without params, i can get orders for my customer correctly.

But when i use **commerce.customer.getOrders()** method from commerce library i get an error 500. 
I've seen that this method call the endpoint with parameters "?sortBy=created&sortDirection=desc". When i try to call the endpoint with that params in Postman i get the error 500. 

So i guess there is a problem with the sort filter on this endpoint.

i'm using the "@chec/commerce.js": "^2.3.2"

Thanks

**Comment by robbieaverill** [comment]
Hi @zb2oby, please use `created_at` for sort column filtering. The API should not return a 500 error when you use `created` though, I will fix that up on our side. Thanks for reporting the issue!
