### ISSUE TITLE
can't retrieve products after passing category_slug as additional parameter

### ISSUE THREAD

**Issue by Anishshettyk** [chec/commerce.js#156]
steps to reproduce,
pass category slug as a additional parameter to retrieve some products but returns this error

![error](https://user-images.githubusercontent.com/47324253/116247958-ff90c280-a788-11eb-9a97-0627f1e6c3f4.JPG)

and the code to reproduce this is,
`const limit = 50;
    const categorySlug = 'men-sneakers';
    commerce.products
      .list({
        limit: limit,
        category_slug: categorySlug,
      })
      .then((response) => response.data);`

produces same result when passing category id instead of category slug

**Comment by robbieaverill** [comment]
Hi there, the slug must be an array
