### ISSUE TITLE
customer.getOrders() Promise

### ISSUE THREAD

**Issue by PaitoAnderson** [chec/commerce.js#171]
When calling `customer.getOrders()` / `customer.getOrder()` I've noticed you get a bunch of the information regarding the request included instead of just the `data` prop.

Can I open a PR to fix or is this intended? I understand it would be a breaking change.

```js
commerce.customer.getOrders()
  .then((response) => {
   console.log(response);
  });
```
<img width="692" alt="Screen Shot 2021-06-08 at 10 31 16 AM" src="https://user-images.githubusercontent.com/4108718/121204201-b8e0be80-c844-11eb-9de1-cbc4ec8a5d53.png">

**Comment by ScopeyNZ** [comment]
It doesn't match with the rest of the SDK, so I agree it's a bug. I think you're fine to fix this despite it being a breaking change.

**Comment by robbieaverill** [comment]
I agree too, let's fix it
