### ISSUE TITLE
Custom meta fields

### ISSUE THREAD

**Issue by amaau** [chec/commerce.js#178]
It would be really wonderful if you'd allow adding custom fields to objects like products and categories. A lot of shops (maybe most) could then use commerce.js on its own, without needing to sync it to another system.

We're using commercejs together with a whole custom backend, syncing products, categories and merchant info, and all because we couldn't add a few fields to a product.

**Comment by robbieaverill** [comment]
Hi @amaau, the product object (and most other objects in our system) have a meta attribute you can use for this. It's an API-only feature, and can be modified using the 'create product' or 'update product' APIs. Docs here: https://commercejs.com/docs/api/#create-product

**Comment by eufandem** [comment]
@amaau is Robbie's suggestion reasonable, or are you looking for something different/ more?

**Comment by amaau** [comment]
Many thanks! Sorry for checking only the gui
