### ISSUE TITLE
Listing shipping countries does not work

### ISSUE THREAD

**Issue by onumengine** [chec/commerce.js#181]
Calling commerce.services.localeListShippingCountries in componentDidMount returns an empty array

**Comment by ScopeyNZ** [comment]
`commerce.services.localeListShippingCountries` needs your checkout token, and will return shipping countries that are valid for the checkout based on the products within the checkout. Either something in the code of your site, or the configuration of the products in your checkout will be causing the empty array.

Either way, I'm sorry but we need more information to determine if there's actually an issue here. Please feel free to add more details and reopen this issue if you feel there's a problem with Commerce.js itself. 

Thanks!
