### ISSUE TITLE
Add option to disable the check preventing you from using a secret key

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#187]
If people want to use Commece.js in a node.js or server side context, this check isn't necessary. Developers may want to use the underlying request helper to call endpoints that are not covered by Commerce.js' JavaScript API. We can add a config flag like `allowSecretKey: true` to override the error that is thrown in the constructor when you use one.

**Comment by amaau** [comment]
Addressed in [this PR](https://github.com/chec/commerce.js/pull/188)

**Comment by robbieaverill** [comment]
@amaau you can use this in v2.8.0 now. Thanks for contributing.
