### ISSUE TITLE
Return assets from category children on listCategories()

### ISSUE THREAD

**Issue by jschneider33** [chec/commerce.js#189]
Is it possible to return the assets of category children with one `listCategories()` call instead of having to retrieve each child from a `category_slug` or `category_id`? Currently it seems to only return the assets of the top-most level category. 

For example, I have multiple parent categories (for ex. `size`) and have added assets to each categories children (`small`, `medium`, and `large`). When I call `listCategories()` it returns size, size's assets, and a list of size's children (`id`, `slug`, `name`) but to get assets for `size -> small` I have to `retrieveCategory("size_id")`. Is this the most effective way to do this?

**Comment by robbieaverill** [comment]
Hi @jschneider33, we think this is a reasonable request, will get it into the backlog to do in the next couple of weeks.
