### ISSUE TITLE
❌ HTTP ERROR [404] Type: Not Found

### ISSUE THREAD

**Issue by aymanouch** [chec/commerce.js#208]
GEThttps://api.chec.io/v1/checkouts/prod_p6dP5g019Wln7k
[HTTP/2 404 Not Found 263ms]

❌ HTTP ERROR [404] Type: Not Found index.js:1
Product not found. index.js:1
id="prod_p6dP5g019Wln7k"

`async function genToken(id) {
    await commerce.checkout.generateToken(id)
     .then(checkout => console.log(checkout.id));
  }`

the product is exist

**Comment by robbieaverill** [comment]
Hi there, is your product set to active? Inactive products may not be accessed with your public API key.

**Comment by aymanouch** [comment]
sorry is my fault I solve the problem like this add the object {type:"cart"} 
thank you bro 👌👌👌👌

`async function genToken(id) {
    await commerce.checkout.generateToken(id, {type:"cart"})
     .then(checkout => {
      setChkId(checkout.id);
      setGateWaysId(checkout.gateways.manual);
     });
  }`
