### ISSUE TITLE
Products.retrieve returns incorrect type for Variant Group assets / incorrect value for price

### ISSUE THREAD

**Issue by TheRealSamGamgee** [chec/commerce.js#212]
Products.retrieve returns the following array of objects:
```
// variant_groups field returned on products.retrieve response. I've replaces some values with ... for clarity
"variant_groups": [
  {
    "id": "...",
    "name": "...",
    "meta": null,
    "created": ...,
    "updated": ...,
    "options": [
      {
        "id": "...",
        "name": "...",
        "price": { // Does not match what I have configured
          "raw": 0,
          "formatted": "0.00",
          "formatted_with_symbol": "$0.00",
          "formatted_with_code": "0.00 USD"
        },
        "assets": [
          "ast_ZM8X5nLNbNwpv4" // string[], rather than Asset[]
        ],
        "meta": null,
        "created": ...,
        "updated": ...
      },
      {
        "id": "...",
        "name": "...",
        "price": {
          "raw": 0,
          "formatted": "0.00", // Does not match what I have configured
          "formatted_with_symbol": "$0.00",
          "formatted_with_code": "0.00 USD"
        },
        "assets": [
          "ast_gvRjwOVWABl4mN" // string[], rather than Asset[]
        ],
        "meta": null,
        "created": ...,
        "updated": ...
      }
    ]
  }
]
```

According to the Typescript function / type signatures, the expected type for "assets" is an array of objects matching the Asset interface (should be the same as the "assets" field on the higher-level Product object, which returns all assets for the product):
```
interface Asset {
    id: string;
    url: string;
    description: string | null;
    .... etc.
}
```
Instead an array of strings is being returned. Not a huge deal because I'm still able to get the asset by matching the asset string in variant-group.options.assets with product.assets, but the workaround requires some extra work and suppressing typescript errors.

Also, the price values given in the variant_groups.options.price objects do not match what I have configured and are always 0.

**Comment by robbieaverill** [comment]
> According to the Typescript function / type signatures, the expected type for "assets" is an array of objects matching the Asset interface 

This is a mistake: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chec__commerce.js/types/product-variant-group.d.ts#L17. It should be `string[]` as it is an array of asset IDs like in your example. The idea with this is that the assets are also returned in the product response higher up, so no need to duplicate the whole asset object, as you've said "by matching the asset string in variant-group.options.assets with product.assets".

I will make a patch to update the TypeScript definitions.

Regarding your prices, can you provide a merchant ID and product ID I could take a look at?

**Comment by robbieaverill** [comment]
I've raised a PR to update the TS definitions: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57057

Please ping me (@robbieaverill) on our [community Slack](http://slack.commercejs.com) and we can take a look at your price issues.
