### ISSUE TITLE
Customer `about` method should support customerId and token arguments 

### ISSUE THREAD

**Issue by cpv123** [chec/commerce.js#216]
The `customer.about()` method assumes that the customer token and Id will be available through `this.token()` and `this.id()`, respectively. But if performing authentication logic on the server-side like in a Next.js API route, this won't be the case,

The method should probably allow optional arguments for customer token and Id for cases like this, which is already what is being done by the `customer.getOrder()` method using the `_assertArgsProvided` helper: https://github.com/chec/commerce.js/blob/master/src/features/customer.js#L111

Something like
```js
about(customerId = null, token = null) {
  this._assertArgsProvided(customerId, token)

  return this._request(
    `customers/${customerId || this.id()}`,
    'get',
    {},
    {},
    token,
  )
}
```
would then allow the method to be called from an API route like
```js
const customerToken = getTokenFromCookie()
const customerId = getIdFromCookie()

const customer = await commerce.about(customerToken, customerId)
```
---

FYI the current workaround (which is perfectly fine) was to call the `customer._request()` method directly:
```js
const customerToken = getTokenFromCookie()
const customerId = getIdFromCookie()

const customer = await commerce._request_(
  `customers/${customerId}`,
  'get',
  {},
  {},
  token,
)
```

**Comment by robbieaverill** [comment]
I've marked this as a bug, I agree that it should work this way. We may be able to patch this in v2 as well as considering it for v3.
