### ISSUE TITLE
Commerce.js encodes nested parameters in requests

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commerce.js#221]
Right now, Commerce.js (v2) doesn't properly encode request parameters that have nesting. 

For example, 

```commerce.products.list({ attributes: { attr_123: 'query' }})```

will cause a request that looks like: 

```attributes=%7B%22attr_123%22:%22query%22%7D```

where it should be

```attributes[attr_123]=query```

**Comment by robbieaverill** [comment]
I just merged the PR but it might be worth adding a test for it too

**Comment by ScopeyNZ** [comment]
I considered writing a test, but because it's at the axios level it was a bit complicated - we're currently just intercepting calls to axios in tests.
