### ISSUE TITLE
Using `cart.retrieve` with an expired cart ID silently fails

### ISSUE THREAD

**Issue by jaepass** [chec/commerce.js#23]
It would be nice if a cart was always retrieved with `cart.retrieve` even if it's using an expired cart ID.

**Comment by robbieaverill** [comment]
I believe the cart gets cleared when you checkout. We could create a new one instead of returning an error?

**Comment by robbieaverill** [comment]
So the problem here would be if you come back to your site after a while, the cookie retains a cart ID that may not exist any more? If so, maybe we can catch 404s for retrieving an existing cart and regenerate the cart ID?

**Comment by ScopeyNZ** [comment]
I've just noticed that this is fixed in `master` but not released yet 🤦‍♂
