### ISSUE TITLE
Site is down - can't connect nor fetch data

### ISSUE THREAD

**Issue by Jon104** [chec/commerce.js#243]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/9216560/196319689-f8b74912-e22b-43c9-9585-134af29da86b.png">

**Comment by steveanthony999** [comment]
Came here to post about this!

**Comment by dvnkshl** [comment]
We're looking into this now.

**Comment by markfazzio** [comment]
Glad I am not alone! Facing same issue trying to authenticate via my React + Gatsby app.

**Comment by dvnkshl** [comment]
We've identified the issue. Working through it now. (our provider updated our kubernetes version which broke a few config files)

**Comment by dvnkshl** [comment]
Back online

**Comment by steveanthony999** [comment]
Thank you Devan!!
