### ISSUE TITLE
Be more declarative with adding products to the cart

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commerce.js#25]
Currently the API for adding products to cart is:

```
add(item = {
  id,
  quantity,
  variant,
});
```

Given the fact that carts and products share the `quantity` attribute, but they mean different things, I suggest we change it to be:

```
add(
  id,
  quantity = 1,
  variant = null
)
```

We should also try to extract the ID from the first argument if the whole product entry is passed. This would mean you can do:

```
const product = await products.get(productId);

cart.add(product)
// Or
cart.add(product.id)
```

**Comment by robbieaverill** [comment]
We could sneak this into 2.0 now. If we wait then we will need to be crafty with backwards compatibility.
