### ISSUE TITLE
This project is still live?

### ISSUE THREAD

**Issue by sirion1987** [chec/commerce.js#258]
Is still live?

**Comment by dvnkshl** [comment]
The project is still active; however, development is frozen until we can ensure profitability or find new ownership.

New Developer Plan
We're introducing a free Developer Plan for testing and building on our platform.

Standard Plan Update
Starting October 16th, a minimum charge will apply to live merchants on the Standard Plan. "Live merchants" are defined as those with a live gateway enabled and live sales going through. This minimum charge will apply to all merchants selling less than $500 per month.
