### ISSUE TITLE
Update console helper so it doesn't have a white background

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#29]
This doesn't look great in modern browsers with dark mode, etc.

![image](https://user-images.githubusercontent.com/5170590/70086702-c110cb80-15c7-11ea-821a-215156929c67.png)

**Comment by ScopeyNZ** [comment]
https://github.com/chec/api.v1/blob/babba35d8c1cebc2a844a6ad70e73aafc6800ef0/api/Modules/Cart/Models/Cart.php#L265

**Comment by ScopeyNZ** [comment]
I'm not sure there's a good way to detect dark mode. I had a quick 10 minute investigation. Maybe we should just remove the colouring but leave in the emojis?

**Comment by robbieaverill** [comment]
Fixed in #75, thank you @GuyKh
