### ISSUE TITLE
cart.refresh() should return the cart, rather than the cart ID

### ISSUE THREAD

**Issue by john-raymon** [chec/commerce.js#31]
Should we create a getter method within the root `commerce.js` class that proxies/returns the `cart` instance variable that's within the `Features.Cart` instance created within `commerce.js` that's assigned as `this.cart`? 

A use-case is:
(two methods within a React.Component)
```
// retrieveCart
retrieveCart(){
    commerce.cart.retrieve().then(cart => {
      this.setState({
        cart
      })
    }).catch(error => console.log(error));
  }

// refreshes cart
refreshCart(){
    commerce.cart.refresh().then(resp => {
      this.retrieveCart() 
      // instead of invoking this.retrieveCart to retrieve the new/refreshed cart 
      // we should avoid an additional request (commerce.cart.retrieve internally invokes commerce.cart.request method, as does commerce.cart.refresh)
      // instead we can ref the cart object that's an  instance variable in commerce.cart (ex: commerce.cart.cart)
      // (it used to only have the cartId ex. commerce.cart.cartId)
      this.setState({
        cart: commerce.cart.cart
      })
    }).catch(error => console.log(error))
  }
```

The issue with this is that a developer won't know the `cart` instance variable exist within  `commerce.cart` unless they debugged, or got into the source code. I think having a getter within the root `commerce` class like commerce.cartObject that returns the `cart` object instance variable living within `commerce.cart` as `commerce.cart.cart`.

**Comment by robbieaverill** [comment]
In that example it seems as if the `cart.refresh()` method should return the cart in its response

**Comment by ScopeyNZ** [comment]
> In that example it seems as if the `cart.refresh()` method should return the cart in its response

Agreed.

What I don't want is for this SDK to be used for state management. That should be up to your app.

**Comment by robbieaverill** [comment]
Just read that method. It's not super clear what it's for to be honest, but if it's just creating a new cart then your example should really become `commerce.cart.refresh().then(() => this.setState({ cart: {} }))` right?

**Comment by john-raymon** [comment]
> In that example it seems as if the `cart.refresh()` method should return the cart in its response

This isn't 

> > In that example it seems as if the `cart.refresh()` method should return the cart in its response
> 
> Agreed.
> 
> What I don't want is for this SDK to be used for state management. That should be up to your app.

How does this get into state management? The refresh method returns a `Promise` that is resolved with only a `cart_id`? Which is why in the example I'm forced to invoke the `commerce.cart.retrieveCart` which if you look at the source code it is doing a whole other subsequent `commerce.cart.request`. When `commerce.cart.refresh` is invoked initially, internally it gets a new cart, saves it to `this.cart` but then returns only the cart id, which is I'm saying that it's clear/obvious that one will need to do `commerce.cart.cart.` when the `commerce.cart.refresh()` promise resolves? It leads to the consumer of the SDK, invoking the `commerce.cart.retrieve`. had the `commerce.cart.refresh` returned (see this [line](https://github.com/chec/commerce.js/blob/master/src/features/cart.js#L20)) then we could just get the new refreshed cart object from within the thenables callback, or how it works right now `commerce.cart.cart` or how I'm proposing, a simple call method (getter) that just returns commerce.cart.cart, or just make this https://github.com/chec/commerce.js/blob/master/src/features/cart.js#L20 return `cart` not the carts id.

**Comment by john-raymon** [comment]
> Just read that method. It's not super clear what it's for to be honest, but if it's just creating a new cart then your example should really become `commerce.cart.refresh().then(() => this.setState({ cart: {} }))` right?

but i want the newly refreshed cart and it's meta data in the state, not an empty javascript object. The `commerce.cart.refresh` method actually request and gets a cart object. See, https://github.com/chec/commerce.js/blob/master/src/features/cart.js#L16. I would want that too on the front-end internal state, not a empty `{}` as the refreshed cart.

**Comment by ScopeyNZ** [comment]
Ok the issue here is that `refresh` should give you back the cart.

I wasn't implying that `cart.refresh` returning the cart gets into state management, but providing and recommending API that exposes the internal `.cart` object would be.

**Comment by john-raymon** [comment]
> Ok the issue here is that `refresh` should give you back the cart.
> 
> I wasn't implying that `cart.refresh` returning the cart gets into state management, but providing and recommending API that exposes the internal `.cart` object would be.

Ah I see, sorry. What do you recommended is the best solution here?

**Comment by robbieaverill** [comment]
Make `cart.refresh` return the new cart object rather than the ID? Should be an easy change to make, and we can still do this for v2

**Comment by john-raymon** [comment]
> Make `cart.refresh` return the new cart object rather than the ID? Should be an easy change to make, and we can still do this for v2

That sounds simple enough, think I overthought it
