### ISSUE TITLE
Create a process to upload versions of commerce.js to CDN on release

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commerce.js#32]
The build process of `commerce.js` creates some bundles that can be used inside traditional `<script>` tags if you don't want to mess around with NPM. We should figure out a process (probably during `npm publish`) that will upload these scripts to a CDN.

**Comment by robbieaverill** [comment]
Do we want to upload every version individually, i.e. v1.0.0, v1.0.1, v1.1.0, v2.0.0, as well as one for each major version, e.g. v1 and v2? Or just the latter, and encourage people to use NPM for specific versions?

**Comment by ScopeyNZ** [comment]
I was thinking that we'd upload per major.

**Comment by robbieaverill** [comment]
We could add this to CircleCI to auto-deploy to our CDN.

**Comment by ScopeyNZ** [comment]
I just tried publishing a new release and the tag did not prompt the workflow to start on Circle, so something's wrong here.

**Comment by dvnkshl** [comment]
@ScopeyNZ any movement on this?

**Comment by ScopeyNZ** [comment]
The CDN has the 2.0.0 release that @robbieaverill tagged yesterday so I assume I fixed this and forgot to update the issue!
