### ISSUE TITLE
Write a v1 to v2 migration guide, highlighting API changes such as cart.add

### ISSUE THREAD

**Issue by john-raymon** [chec/commerce.js#33]
Should we maintain the same argument definition from `v1` for the `cart.add` method?

I was trying to pin-point why the request to the `cart` endpoint, adding a product to the cart, was not providing the `variant` in the body.
This was because I was assuming the `v2` `cart.add` still accepted a single argument as an object with `id`, `quantity`, and `variant` properties, however, now it's not an object but individual parameters. 

https://github.com/chec/commerce.js/blob/925909d61a9aa37bc4884673c82465e002d4f49a/src/features/cart.js#L81

`v1` cart.add looks like this
![image](https://user-images.githubusercontent.com/30238579/70380166-ff2e2800-1904-11ea-9b8c-59b21fe6c766.png)

**Comment by robbieaverill** [comment]
We changed this deliberately to make it easier to use: https://github.com/chec/commerce.js/issues/25

We could add backwards compatibility for the previous structure but I don’t want to change it back, it’s a good change and v2 allows us to make it safely. The v1 signature should be treated as deprecated.

**Comment by john-raymon** [comment]
> We changed this deliberately to make it easier to use: #25
> 
> We could add backwards compatibility for the previous structure but I don’t want to change it back, it’s a good change and v2 allows us to make it safely. The v1 signature should be treated as deprecated.

Ah, I missed that. I think I like the change. Is this something that I should add to the readme?

**Comment by robbieaverill** [comment]
We could definitely add a migration guide for v1-v2!

**Comment by robbieaverill** [comment]
I've updated the issue title, let's make this a docs task rather than logic

**Comment by ScopeyNZ** [comment]
We have some very limited docs already: https://github.com/chec/commerce.js#upgrading
