### ISSUE TITLE
Ensure auto-deployments purge the CDN cache

### ISSUE THREAD

**Issue by ScopeyNZ** [chec/commerce.js#45]
We have auto-deployments when we push tags which is nice, but the CDN doesn't update without an explicit request to purge the file from the edges. There's probably some way to configure this in the AWS CLI that we use. I'm not sure if that will be compatible with the CDN provider we use, or whether we'll need to do something else.

**Comment by robbieaverill** [comment]
How long is our cache TTL?

**Comment by ScopeyNZ** [comment]
One hour.

**Comment by robbieaverill** [comment]
I can live with that

**Comment by robbieaverill** [comment]
One hour is fine. We encourage the use of Commerce.js via NPM over the CDN as well.
