### ISSUE TITLE
How to use dotenv with commerce.js?

### ISSUE THREAD

**Issue by jrmarqueshd** [chec/commerce.js#48]
I'm try to use the lib [https://www.npmjs.com/package/dotenv](dotenv) but not working, how to use env with commerce.js?

**Comment by john-raymon** [comment]
Hey @jrmarqueshd 👋🏽

You can read more about initializing Commerce.js with your public API key here, https://commercejs.com/docs/overview/getting-started.html#installing-the-sdk-via-our-cdn. 

If you'd like to utilize the `dotenv` lib to load variables from an `.env`, this guide may help you; http://zetcode.com/javascript/dotenv/.

I imagine something like this is what you're looking for
```
require('dotenv').config()

const commerce = new Commerce(process.env.CHEC_PUBLIC_API_KEY);
```
