### ISSUE TITLE
Add helper to "carts" module for checking available stock level for a product

### ISSUE THREAD

**Issue by robbieaverill** [chec/commerce.js#49]
We have this helper function: https://commercejs.com/docs/api/#check-requested-quantity

It requires a checkout token ID to work, which means it can't be used before you get to the checkout.

If a developer wants to check the stock level when adding to cart, or async after doing so, they would have to fetch the product's data `GET /v1/products/{id}` just to get the stock level out of it, and have their own comparison logic.

We could make an equivalent of this method but in the carts namespace which won't require a checkout token.

**Comment by talentedunicorn** [comment]
Can I give this a go? :upside_down_face:

**Comment by ScopeyNZ** [comment]
Go for it! You can get multiple products by ID by using something like `/v1/products?query=prod_123,prod_456`, which might help for this task.

**Comment by AnshMishra2001** [comment]
Can I work on this issue,pls ?

**Comment by robbieaverill** [comment]
Anyone is welcome to contribute, we'll welcome any pull requests 😃

**Comment by ritesh-pandey** [comment]
Please let me know if I understood the problem statement correctly.

There can be multiple products in a cart with different quantities. We need a helper function to check if current cart quantity is valid or not. Validity is decided by comparing product quantity available in stock (product API) and quantity added in cart (present locally).

**Comment by sanket143** [comment]
@robbieaverill how can we add it in `carts` namespace? Will it be appropriate to do ```this.commerce.request(`products/${id}`)``` in `cart.js`?

**Comment by robbieaverill** [comment]
Yep, sounds reasonable
