### ISSUE TITLE
Wrong order of docs markdown files with number prefix

### ISSUE THREAD

**Issue by jaepass** [chec/commerce.js#74]
The order in which the sdk docs appear in nav is wrong even though the order number prefix is correct. In particular the checkout link should come before concepts.

<img width="333" alt="Screen Shot 2020-09-28 at 5 22 24 PM" src="https://user-images.githubusercontent.com/48780927/94498514-3977f700-01af-11eb-9a95-4ef21153c7ff.png">

**Comment by abraaoduarte** [comment]
I would like to work on it.

**Comment by robbieaverill** [comment]
Hey @abraaoduarte, thanks for reaching out. I actually don't think there's anything you could fix in this repository for this problem, it's something we need to handle on our private website repository. I'll remove the hacktoberfest label. Sorry!

**Comment by robbieaverill** [comment]
I think we can probably fix this on our end, closing.

**Comment by jaepass** [comment]
This was fixed while back in a marketing issue should have closed this 🙈
