### ISSUE TITLE
Enhance contributing guidelines

### ISSUE THREAD

**Issue by ng29** [chec/commerce.js#81]
Would like to update  contributing.md file
similar to https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/CONTRIBUTING.md if you are ok with the design I woud like to design contributing.md file for this project too please assign the issue to me

**Comment by jaepass** [comment]
Hi there thanks for the interest but we have a contributing guide for this repo already so it won't be necessary! Thanks again!
