### ISSUE TITLE
Adding proper documentation

### ISSUE THREAD

**Issue by sharur7** [chec/commerce.js#82]
Adding proper documentation:
Code of Conduct
Issue Template
Pull Request Template

**Comment by sharur7** [comment]
@robbieaverill Please check if this issue is valid or not? I want to work on this by myself

**Comment by robbieaverill** [comment]
Thanks for raising this issue. I'm happy with the contributing guide we have, and we don't want the templates mentioned. If you find typos etc you're welcome to make a PR to fix those, but I'm going to close this issue for now.
